#!/usr/bin/env tsx
/**
 * Discover YouTube auto-generated Topic channels for a curated artist list.
 *
 * Topic channels follow the pattern: "{Artist} - Topic" with a description
 * starting "Auto-generated by YouTube." They aggregate the audio-only versions
 * of every track in YouTube's catalog for that artist — and are a second
 * revenue leg for the labels TIPS / Saregama beyond their owned channels.
 *
 * Usage:
 *   YOUTUBE_API_KEY=... npx tsx scripts/discover-topic-channels.ts
 *
 * Cost: 100 quota units per search.list call. Default seed = ~35 artists →
 * ~3500 quota units. One-off.
 *
 * Output: JSON to stdout. Pipe to a file, review, then bulk-insert into
 * dim_channel via Supabase MCP (manual step — see end of script for SQL).
 */

const YT_API = 'https://www.googleapis.com/youtube/v3';
const KEY = process.env.YOUTUBE_API_KEY;
if (!KEY) {
  console.error('YOUTUBE_API_KEY environment variable required.');
  process.exit(1);
}

type Label = 'TIPSMUSIC' | 'SAREGAMA' | 'shared';

interface ArtistSeed {
  name: string;
  primary: Label;
  /** Optional: per-label catalog share (defaults: TIPS=1.0, SARE=1.0, shared={TIPS:0.5, SARE:0.5}) */
  share?: Partial<Record<'TIPSMUSIC' | 'SAREGAMA', number>>;
  /** Why this artist matters — for IR rationale on the bulk insert. */
  note?: string;
}

// =============================================================================
// Curated seed list. Attribution reflects whose catalog is most prominent for
// the artist on the labels we track. Soft weights via `share` capture cases
// where catalog is split (e.g. legacy Bollywood vocalists span multiple labels).
//
// Refine this list before running by adding/removing artists. The script
// validates "{Artist} - Topic" matches exactly + "Auto-generated by YouTube"
// in description, so namesakes / fan channels won't pollute results.
// =============================================================================
const ARTISTS: ArtistSeed[] = [
  // --- TIPS-leaning modern catalog (Bollywood + Punjabi, 1990s+) ----------------
  { name: 'Atif Aslam',          primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.7 }, note: 'TIPS has key film catalog' },
  { name: 'Mohit Chauhan',       primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.6 } },
  { name: 'Hardy Sandhu',        primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.8 }, note: 'TIPS Punjabi flagship' },
  { name: 'Guru Randhawa',       primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.7 } },
  { name: 'Yo Yo Honey Singh',   primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.6 } },
  { name: 'Diljit Dosanjh',      primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.5 } },
  { name: 'Jubin Nautiyal',      primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.5 } },
  { name: 'Tulsi Kumar',         primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.4 } },
  { name: 'KK',                  primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.5 }, note: 'film catalog split TIPS/SARE' },
  { name: 'Rahat Fateh Ali Khan', primary: 'TIPSMUSIC', share: { TIPSMUSIC: 0.5 } },

  // --- Saregama-leaning classic catalog (1950s–1990s) ------------------------
  { name: 'Lata Mangeshkar',     primary: 'SAREGAMA',  share: { SAREGAMA: 0.85 }, note: 'Saregama owns HMV legacy' },
  { name: 'Asha Bhosle',         primary: 'SAREGAMA',  share: { SAREGAMA: 0.85 } },
  { name: 'Mohammed Rafi',       primary: 'SAREGAMA',  share: { SAREGAMA: 0.9 } },
  { name: 'Kishore Kumar',       primary: 'SAREGAMA',  share: { SAREGAMA: 0.85 } },
  { name: 'Mukesh',              primary: 'SAREGAMA',  share: { SAREGAMA: 0.9 } },
  { name: 'Manna Dey',           primary: 'SAREGAMA',  share: { SAREGAMA: 0.9 } },
  { name: 'R. D. Burman',        primary: 'SAREGAMA',  share: { SAREGAMA: 0.8 }, note: 'composer; many films via HMV' },
  { name: 'S. D. Burman',        primary: 'SAREGAMA',  share: { SAREGAMA: 0.85 } },
  { name: 'Bappi Lahiri',        primary: 'SAREGAMA',  share: { SAREGAMA: 0.6 } },
  { name: 'Geeta Dutt',          primary: 'SAREGAMA',  share: { SAREGAMA: 0.9 } },
  { name: 'Hemant Kumar',        primary: 'SAREGAMA',  share: { SAREGAMA: 0.9 } },
  { name: 'Sandhya Mukherjee',   primary: 'SAREGAMA',  share: { SAREGAMA: 0.9 }, note: 'Bengali catalog' },
  { name: 'Madan Mohan',         primary: 'SAREGAMA',  share: { SAREGAMA: 0.85 } },

  // --- Shared / omnipresent (catalog split across many labels) ---------------
  { name: 'Arijit Singh',        primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.3 } },
  { name: 'Shreya Ghoshal',      primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.3 } },
  { name: 'Sonu Nigam',          primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.3 } },
  { name: 'Udit Narayan',        primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.4 } },
  { name: 'Alka Yagnik',         primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.4 } },
  { name: 'Kumar Sanu',          primary: 'shared',    share: { TIPSMUSIC: 0.4, SAREGAMA: 0.4 } },
  { name: 'Anuradha Paudwal',    primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.4 } },
  { name: 'A. R. Rahman',        primary: 'shared',    share: { TIPSMUSIC: 0.2, SAREGAMA: 0.2 } },
  { name: 'Pritam',              primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.2 } },
  { name: 'Vishal-Shekhar',      primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.2 } },
  { name: 'Sachin-Jigar',        primary: 'shared',    share: { TIPSMUSIC: 0.3, SAREGAMA: 0.2 } },
];

interface Candidate {
  artist: string;
  primary: Label;
  share: Partial<Record<'TIPSMUSIC' | 'SAREGAMA', number>>;
  note?: string;
  channelId: string;
  title: string;
  subscribers: number;
  views: number;
}

interface SearchItem {
  snippet: {
    title: string;
    description: string;
    channelId: string;
  };
}

interface ChannelStatsItem {
  id: string;
  snippet: { title: string };
  statistics: { subscriberCount?: string; viewCount?: string };
}

/**
 * Topic channels are squatted heavily on YouTube — for any popular artist you
 * get 10+ channels titled "{Artist} - Topic" with single-digit subscriber
 * counts plus the canonical one with millions of subs. Strategy:
 *
 *   1. search.list q="{Artist} - Topic" maxResults=25 (100 quota units)
 *   2. Filter to title ∈ { "{Artist} - Topic", "{Artist} Topic" } (case-insensitive)
 *   3. Batch the candidate IDs through channels.list (1 quota per 50 IDs)
 *   4. Pick the one with the highest subscriber count, requiring ≥ 10k subs
 *      to filter spam
 */
async function searchTopicCandidates(seed: ArtistSeed): Promise<string[]> {
  // YT search treats quoted strings containing punctuation (the dash in
  // "Atif Aslam - Topic") restrictively and silently drops valid results.
  // Use a relaxed query and rely on the title-match filter for precision.
  const q = `${seed.name} Topic`;
  const url =
    `${YT_API}/search?part=snippet&q=${encodeURIComponent(q)}` +
    `&type=channel&maxResults=25&key=${KEY}`;
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`  ✗ ${seed.name}: search HTTP ${res.status}`);
    return [];
  }
  const data = (await res.json()) as { items?: SearchItem[] };
  const dashed = `${seed.name.toLowerCase()} - topic`;
  const spaced = `${seed.name.toLowerCase()} topic`;
  return (data.items ?? [])
    .filter((i) => {
      const t = (i.snippet.title ?? '').toLowerCase().trim();
      return t === dashed || t === spaced;
    })
    .map((i) => i.snippet.channelId);
}

async function fetchChannelStats(ids: string[]): Promise<ChannelStatsItem[]> {
  if (ids.length === 0) return [];
  const out: ChannelStatsItem[] = [];
  // channels.list takes up to 50 ids per call
  for (let i = 0; i < ids.length; i += 50) {
    const batch = ids.slice(i, i + 50);
    const url =
      `${YT_API}/channels?part=snippet,statistics&id=${batch.join(',')}` +
      `&key=${KEY}`;
    const res = await fetch(url);
    if (!res.ok) {
      console.error(`  ✗ channels.list HTTP ${res.status}`);
      continue;
    }
    const data = (await res.json()) as { items?: ChannelStatsItem[] };
    out.push(...(data.items ?? []));
  }
  return out;
}

async function findTopicChannel(seed: ArtistSeed): Promise<Candidate | null> {
  const candidateIds = await searchTopicCandidates(seed);
  if (candidateIds.length === 0) return null;
  const stats = await fetchChannelStats(candidateIds);
  const ranked = stats
    .map((s) => ({
      id: s.id,
      title: s.snippet.title,
      subs: Number(s.statistics.subscriberCount ?? 0),
      views: Number(s.statistics.viewCount ?? 0),
    }))
    .filter((s) => s.subs >= 10_000) // filter spam Topic channels
    .sort((a, b) => b.subs - a.subs);
  if (ranked.length === 0) return null;
  const top = ranked[0];
  return {
    artist: seed.name,
    primary: seed.primary,
    share: seed.share ?? {},
    note: seed.note,
    channelId: top.id,
    title: top.title,
    subscribers: top.subs,
    views: top.views,
  };
}

async function main() {
  console.error(`Searching for ${ARTISTS.length} Topic channels...`);
  console.error(`Estimated quota cost: ${ARTISTS.length * 100} units.\n`);

  const found: Candidate[] = [];
  const missing: string[] = [];

  for (const seed of ARTISTS) {
    const result = await findTopicChannel(seed);
    if (result) {
      console.error(
        `  ✓ ${seed.name.padEnd(28)} → ${result.channelId} (subs=${result.subscribers.toLocaleString()}, views=${result.views.toLocaleString()})`,
      );
      found.push(result);
    } else {
      console.error(`  ✗ ${seed.name.padEnd(28)} → not found`);
      missing.push(seed.name);
    }
    await new Promise((r) => setTimeout(r, 150));
  }

  console.error(`\nFound ${found.length}/${ARTISTS.length}. Missing: ${missing.join(', ') || 'none'}\n`);

  // --- Emit JSON to stdout for piping/review --------------------------------
  console.log(JSON.stringify(found, null, 2));

  // --- Hint at the SQL the user will run after review ----------------------
  console.error('\n--- Next steps ---');
  console.error('1. Review the JSON above; remove any rows you do not want to track.');
  console.error('2. Apply migration 0009 via Supabase MCP if not already applied.');
  console.error('3. Insert into dim_channel + dim_artist_label using the JSON.');
  console.error('   Example SQL pattern:');
  console.error('     INSERT INTO dim_channel (channel_id, channel_name, channel_type, artist_name, ingest_videos)');
  console.error("     VALUES ('UC...', 'Arijit Singh - Topic', 'topic', 'Arijit Singh', false);");
  console.error("     INSERT INTO dim_artist_label (artist_name, company, catalog_share)");
  console.error("     VALUES ('Arijit Singh', 'TIPSMUSIC', 0.3),");
  console.error("            ('Arijit Singh', 'SAREGAMA', 0.3);");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
